### PR TITLE
feat: add node-expansion module

### PR DESCRIPTION
**Pull request by ericz1803**
This PR addresses https://github.com/biothings/BioThings_Explorer_TRAPI/issues/366 and https://github.com/biothings/BioThings_Explorer_TRAPI/issues/196. 

See and merge together with https://github.com/biothings/bte_trapi_query_graph_handler/pull/113.

### CODE REVIEW

**Comment by colleenXu** [comment]
@ericz1803 @tokebe I cannot get this PR (with the query-handler) working in my local instance. I think it's because I don't know how to hook-up / install the node-expansion module ([here](https://github.com/biothings/node-expansion)?) after checking out these branches. 

<details>
<summary>what I tried doing</summary>

When I checkout the branches, and then run `npm run compile`, I get this error: 

```
➜  bte-trapi-workspace git:(node-expansion) ✗ npm run compile

> compile
> tsc -b tsconfig.build.json

error TS5083: Cannot read file '/Users/colleenxu/Desktop/bte-trapi-workspace/packages/@biothings-explorer/node-expansion/tsconfig.json'.


Found 1 error.
```

I think this implies that the node-expansion module is missing. However, I don't know how to automatically install it. When I go to the bte-trapi-workspace directory and run `npm run clone` (which sets up the modules normally), I think the code does a check and reports that the node-expansion module is missing but it doesn't seem to git-clone/install/add any directories to fix that...

console logs:
```
➜  bte-trapi-workspace git:(node-expansion) ✗ npm run clone

> clone
> ./scripts/clone_packages.sh

Clone repos using https...
++ read -r url module_dir
++ git clone https://github.com/biothings/BioThings_Explorer_TRAPI.git ./packages/@biothings-explorer/bte-trapi
fatal: destination path './packages/@biothings-explorer/bte-trapi' already exists and is not an empty directory.
++ read -r url module_dir
++ git clone https://github.com/biothings/bte_trapi_query_graph_handler.git ./packages/@biothings-explorer/query_graph_handler
fatal: destination path './packages/@biothings-explorer/query_graph_handler' already exists and is not an empty directory.
++ read -r url module_dir
++ git clone https://github.com/biothings/biolink-model.js.git ./packages/biolink-model
fatal: destination path './packages/biolink-model' already exists and is not an empty directory.
++ read -r url module_dir
++ git clone https://github.com/biothings/biomedical_id_resolver.js.git ./packages/biomedical_id_resolver
fatal: destination path './packages/biomedical_id_resolver' already exists and is not an empty directory.
++ read -r url module_dir
++ git clone https://github.com/biothings/smartapi-kg.js.git ./packages/@biothings-explorer/smartapi-kg
fatal: destination path './packages/@biothings-explorer/smartapi-kg' already exists and is not an empty directory.
++ read -r url module_dir
++ git clone https://github.com/biothings/call-apis.js.git ./packages/@biothings-explorer/call-apis
fatal: destination path './packages/@biothings-explorer/call-apis' already exists and is not an empty directory.
++ read -r url module_dir
++ git clone https://github.com/biothings/api-respone-transform.js.git ./packages/@biothings-explorer/api-response-transform
fatal: destination path './packages/@biothings-explorer/api-response-transform' already exists and is not an empty directory.
++ read -r url module_dir
++ cd ./packages/@biothings-explorer/call-apis
++ ln -s ../../../scripts/tsconfig.json_call-apis ./tsconfig.json
ln: ./tsconfig.json: File exists
++ cd /Users/colleenxu/Desktop/bte-trapi-workspace
++ cd ./packages/@biothings-explorer/bte-trapi
++ ln -s ../../../scripts/tsconfig.json_bte-trapi ./tsconfig.json
ln: ./tsconfig.json: File exists
++ cd /Users/colleenxu/Desktop/bte-trapi-workspace
++ cd ./packages/@biothings-explorer/node-expansion
./scripts/clone_packages.sh: line 33: cd: ./packages/@biothings-explorer/node-expansion: No such file or directory
++ ln -s ../../../scripts/tsconfig.json_node-expansion ./tsconfig.json
ln: ./tsconfig.json: File exists
++ cd /Users/colleenxu/Desktop/bte-trapi-workspace
++ set +x
```

Then I tried running `npm i` (the next step of installing bte-trapi-workspace) to see what happened. Then I saw another error that seems to related to the missing node-expansion module...

```
➜  bte-trapi-workspace git:(node-expansion) ✗ npm i

> prepare
> npm run compile


> bte-trapi-monorepo@ compile /Users/colleenxu/Desktop/bte-trapi-workspace
> tsc -b tsconfig.build.json

error TS5083: Cannot read file '/Users/colleenxu/Desktop/bte-trapi-workspace/packages/@biothings-explorer/node-expansion/tsconfig.json'.


Found 1 error.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bte-trapi-monorepo@ compile: `tsc -b tsconfig.build.json`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bte-trapi-monorepo@ compile script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/colleenxu/.npm/_logs/2022-09-01T22_41_27_102Z-debug.log
npm ERR! code 1
npm ERR! path /Users/colleenxu/Desktop/bte-trapi-workspace
npm ERR! command failed
npm ERR! command sh -c npm run compile

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/colleenxu/.npm/_logs/2022-09-01T22_41_21_005Z-debug-0.log
```
</details>

**Comment by colleenXu** [comment]
Something that seems to have worked:
* cd into `bte-trapi-workspace/packages/@biothings-explorer`
* then `git clone` the node expansion module https://github.com/biothings/node-expansion (I use https)
* then cd into `bte-trapi-workspace` (aka `cd ../..`). 
* Run `npm i`, then run `npm run compile`. 

EDIT: I'm not sure if this means that some things in this PR need adjusting / stuff needs doing for each server instance when this is deployed.

**Comment by colleenXu** [comment]
Note that I pushed the merges I made with the latest main...since this code hadn't been in-line with main for a while.

**Comment by tokebe** [comment]
We'll need a PR for the workspace to automate adding the node-expansion module -- It should work if just added to [this file](https://github.com/biothings/bte-trapi-workspace/blob/main/scripts/packages.txt)

**Comment by colleenXu** [comment]
Decision from 9/7 group meeting: @tokebe to review how to deploy new modules: anything to edit/add to this PR? what commands to use when one already has bte-trapi-workspace (same as install instructions: npm run clone, npm i (twice)?).

**Comment by tokebe** [comment]
*(My previous comment was a little silly, I must not have realized what repo the PR was in...)*

I've confirmed there's an issue with how the `packages.txt` file is being read. It's actually rather strange: the file is read properly, except for the last line, but only if there isn't a newline at the end of the file. This causes the current new addition to not be read properly.

I'll push a fix for that into this branch once I have it. After that, the procedure should be relatively simple:

1. Add the package to package.txt (as done in this PR)
2. `npm run clone`
3. `npm i` (worth doing twice as @colleenXu pointed out above)

**Comment by tokebe** [comment]
Fixes have been added.

**Comment by colleenXu** [comment]
I deleted my local directory bte-trapi-workspace/packages/@biothings-explorer/node-expansion, then I used the latest code in this branch and followed Jackson's directions [above](https://github.com/biothings/bte-trapi-workspace/pull/17#issuecomment-1239727405) (npm run clone, then npm i). It looks like the new module installed properly.

**Pull request merged**
