### PR TITLE
Start/stop scripts for debugging w/ redis

### PR DESCRIPTION
**Pull request by tokebe**
*(addresses biothings/BioThings_Explorer_TRAPI/issues/394)*
This PR implements `npm start` and `npm stop` scripts which are able to use either native redis or the `redis:latest` Docker image to start BTE in debug mode with redis enabled.

`npm start` will first check if redis is running natively and flush it if so. Otherwise, it will try docker, or start native redis failing that. If either docker or native are running prior to the stat, it will ensure a clean slate for redis. If neither works, it will display a message and run BTE without redis enabled.

`npm stop` will naively kill any `node` process (planning to update this PR with a better solution prior to merge), and then either remove the redis docker container or flush and stop natively-running redis, depending on which is running.

### CODE REVIEW

**Comment by colleenXu** [comment]
The `npm stop` command seems to work to stop an asyncquery from running. My process is to start up BTE w/ redis (using `npm start` OR `REDIS_HOST=localhost REDIS_PORT=6379 RESULT_CACHING=false npm run debug --workspace='@biothings-explorer/bte-trapi'`), then run a query to the /asyncquery endpoint, then try to stop using `npm stop` (in the running tab or in a new tab).

However, it does look like I need to give the command twice (`npm stop` `npm stop`) before the logs from running the query actually stop...

Also, the commands are a bit confusing to me now:
* it looks like the redis server automatically starts w/ the `npm start` command. But it's not clear to me how to do an `npm start` and NOT run redis. 
* on the other hand, it looks like `npm run debug` will not use redis by default, unless I set the REDIS_* parameters (`REDIS_HOST=localhost REDIS_PORT=6379 RESULT_CACHING=false npm run debug --workspace='@biothings-explorer/bte-trapi'`)...and `npm run debug` is what I normally do to run BTE locally

**Comment by tokebe** [comment]
`npm start` now starts BTE without starting redis, while `npm start redis` will start **both** BTE and redis.

`npm stop` is now hopefully a little more targeted, instead of attempting to wipe out all `node` processes, it searches for processes with `bte-trapi` in the name/arguments (which relies on BTE being started within the workspace). This should capture both the BTE server and bull's process for async. From there all subprocesses of the found processes are killed, then the found processes are killed (all with `SIGKILL`), which should result in the complete and immediate end of any active BTE work in one go, without disrupting other node processes.

**Comment by colleenXu** [comment]
works as I would expect now!
* `npm start` doesn't use redis, `npm start redis` does use redis
* `npm stop` in a different tab does stop the asyncquery that I'm running in another tab

**Comment by colleenXu** [comment]
I will note that it's a bit difficult to tell what all the default parameters are set to (is USE_THREADING true or false if I just run "npm start"?)

**Comment by tokebe** [comment]
Just posting for future reference (covered in slack discussion): `USE_THREADING`, and any other environment variables, are used at their default values for `npm start`, except for `DEBUG`, which is set according to [BTE's debug script](https://github.com/biothings/BioThings_Explorer_TRAPI/blob/99ede62198faa7b369c49b064cd3001264192d0b/package.json#L10), which is used internally for the `npm start` script.

**Pull request merged**
